### ISSUE TITLE
 Переименование репозитория

### ISSUE THREAD

**Issue by mr8bit** [tainella/survive_in_sad_town#1]
Считаю, что наименование данного репозитория дискредитирует Российскую Федерацию вследствие чего его необходимо переименовать.

**Comment by tainella** [comment]
> Считаю, что наименование данного репозитория дискредитирует Российскую Федерацию вследствие чего его необходимо переименовать.

Большое спасибо за Ваш комментарий! Название не несло дискредитирующего характера, но во избежание недоразумений репозиторий будет переименован для большего соответствия тематике.
